
CREATE TABLE IF NOT EXISTS admin_users(id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('SUPERADMIN','ADMIN','EDITOR')),active INTEGER NOT NULL DEFAULT 1,password_hash TEXT,auth_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,must_change INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,last_login TEXT);
CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS titles(id TEXT PRIMARY KEY,slug TEXT NOT NULL UNIQUE,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',type TEXT NOT NULL DEFAULT 'Manhwa',status TEXT NOT NULL DEFAULT 'Ongoing',year INTEGER,author TEXT NOT NULL DEFAULT '',artist TEXT NOT NULL DEFAULT '',tags TEXT NOT NULL DEFAULT '',age_label TEXT NOT NULL DEFAULT 'All ages',direction TEXT NOT NULL DEFAULT 'vertical',origin TEXT NOT NULL DEFAULT '',language TEXT NOT NULL DEFAULT 'Uzbek',publication_status TEXT NOT NULL DEFAULT 'Serializing',featured INTEGER NOT NULL DEFAULT 0,visibility TEXT NOT NULL DEFAULT 'Draft' CHECK(visibility IN ('Draft','Published','Hidden')),seo_title TEXT NOT NULL DEFAULT '',seo_description TEXT NOT NULL DEFAULT '',cover_id TEXT,banner_id TEXT,created_by TEXT REFERENCES admin_users(id) ON DELETE SET NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,deleted_at TEXT,views INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS titles_visibility_updated ON titles(visibility,deleted_at,updated_at);
CREATE TABLE IF NOT EXISTS title_alt_names(id TEXT PRIMARY KEY,title_id TEXT NOT NULL REFERENCES titles(id) ON DELETE CASCADE,name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS genres(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS title_genres(id TEXT PRIMARY KEY,title_id TEXT NOT NULL REFERENCES titles(id) ON DELETE CASCADE,genre_id TEXT NOT NULL REFERENCES genres(id),UNIQUE(title_id,genre_id));
CREATE TABLE IF NOT EXISTS title_editors(id TEXT PRIMARY KEY,title_id TEXT NOT NULL REFERENCES titles(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,UNIQUE(title_id,user_id));
CREATE TABLE IF NOT EXISTS chapters(id TEXT PRIMARY KEY,title_id TEXT NOT NULL REFERENCES titles(id) ON DELETE CASCADE,number NUMERIC(14,4) NOT NULL CHECK(number>=0),name TEXT NOT NULL DEFAULT '',volume TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'Draft' CHECK(status IN ('Draft','Published')),publish_at TEXT,sort_order NUMERIC(14,4) NOT NULL,created_by TEXT REFERENCES admin_users(id) ON DELETE SET NULL,updated_by TEXT REFERENCES admin_users(id) ON DELETE SET NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,deleted_at TEXT,UNIQUE(title_id,number));
CREATE INDEX IF NOT EXISTS chapters_order ON chapters(title_id,deleted_at,sort_order,number);
CREATE INDEX IF NOT EXISTS chapters_public ON chapters(status,publish_at);
CREATE TABLE IF NOT EXISTS assets(id TEXT PRIMARY KEY,title_id TEXT REFERENCES titles(id) ON DELETE CASCADE,chapter_id TEXT REFERENCES chapters(id) ON DELETE CASCADE,original_key TEXT NOT NULL,delivery_key TEXT NOT NULL,thumb_key TEXT,mime TEXT NOT NULL,width INTEGER NOT NULL,height INTEGER NOT NULL,bytes INTEGER NOT NULL,source_bytes INTEGER NOT NULL,filename TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS chapter_pages(id TEXT PRIMARY KEY,chapter_id TEXT NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,asset_id TEXT NOT NULL REFERENCES assets(id),position INTEGER NOT NULL,rotation INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS pages_order ON chapter_pages(chapter_id,position);
CREATE TABLE IF NOT EXISTS upload_jobs(id TEXT PRIMARY KEY,chapter_id TEXT REFERENCES chapters(id) ON DELETE CASCADE,title_id TEXT NOT NULL REFERENCES titles(id) ON DELETE CASCADE,user_id TEXT REFERENCES admin_users(id) ON DELETE SET NULL,name TEXT NOT NULL,total_bytes INTEGER NOT NULL,received_bytes INTEGER NOT NULL DEFAULT 0,lease_token TEXT NOT NULL DEFAULT '',lease_until TEXT NOT NULL DEFAULT '',next_chunk INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'uploading',processed INTEGER NOT NULL DEFAULT 0,total INTEGER NOT NULL DEFAULT 0,error TEXT,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS upload_items(id TEXT PRIMARY KEY,job_id TEXT NOT NULL REFERENCES upload_jobs(id) ON DELETE CASCADE,position INTEGER NOT NULL,name TEXT NOT NULL,storage_key TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',UNIQUE(job_id,position));
CREATE TABLE IF NOT EXISTS audit_logs(id TEXT PRIMARY KEY,user_id TEXT REFERENCES admin_users(id) ON DELETE SET NULL,actor TEXT NOT NULL,action TEXT NOT NULL,entity TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS audit_date ON audit_logs(created_at);
CREATE TABLE IF NOT EXISTS site_settings(id TEXT PRIMARY KEY,name TEXT NOT NULL DEFAULT 'INKORA',description TEXT NOT NULL DEFAULT 'Har sahifada yangi olam.',max_upload_mb INTEGER NOT NULL DEFAULT 100,max_pages INTEGER NOT NULL DEFAULT 500);
CREATE TABLE IF NOT EXISTS login_attempts(id TEXT PRIMARY KEY,identity TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS login_window ON login_attempts(identity,created_at);
CREATE TABLE IF NOT EXISTS view_events(id TEXT PRIMARY KEY,title_id TEXT NOT NULL REFERENCES titles(id) ON DELETE CASCADE,day TEXT NOT NULL);

-- Browser clients cannot write privileged data. All mutations use authenticated
-- server routes; server service-role queries are guarded by application RBAC.
CREATE OR REPLACE FUNCTION public.inkora_role() RETURNS TEXT LANGUAGE SQL STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT role FROM admin_users WHERE auth_id=auth.uid() AND active=1 AND must_change=0 LIMIT 1 $$;
CREATE OR REPLACE FUNCTION public.inkora_can_edit(target TEXT) RETURNS BOOLEAN LANGUAGE SQL STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.inkora_role() IN ('SUPERADMIN','ADMIN') OR EXISTS(SELECT 1 FROM title_editors e JOIN admin_users a ON a.id=e.user_id WHERE a.auth_id=auth.uid() AND a.active=1 AND a.must_change=0 AND e.title_id=target) $$;
CREATE OR REPLACE FUNCTION public.inkora_public_title(target TEXT) RETURNS BOOLEAN LANGUAGE SQL STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM titles WHERE id=target AND visibility='Published' AND deleted_at IS NULL) $$;
CREATE OR REPLACE FUNCTION public.inkora_public_chapter(target TEXT) RETURNS BOOLEAN LANGUAGE SQL STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM chapters WHERE id=target AND status='Published' AND deleted_at IS NULL AND (publish_at IS NULL OR publish_at::timestamptz<=now()) AND public.inkora_public_title(title_id)) $$;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.admin_users FROM anon, authenticated;
GRANT ALL ON public.admin_users TO service_role;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.sessions FROM anon, authenticated;
GRANT ALL ON public.sessions TO service_role;
ALTER TABLE public.titles ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.titles FROM anon, authenticated;
GRANT ALL ON public.titles TO service_role;
ALTER TABLE public.title_alt_names ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.title_alt_names FROM anon, authenticated;
GRANT ALL ON public.title_alt_names TO service_role;
ALTER TABLE public.genres ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.genres FROM anon, authenticated;
GRANT ALL ON public.genres TO service_role;
ALTER TABLE public.title_genres ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.title_genres FROM anon, authenticated;
GRANT ALL ON public.title_genres TO service_role;
ALTER TABLE public.title_editors ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.title_editors FROM anon, authenticated;
GRANT ALL ON public.title_editors TO service_role;
ALTER TABLE public.chapters ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.chapters FROM anon, authenticated;
GRANT ALL ON public.chapters TO service_role;
ALTER TABLE public.assets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.assets FROM anon, authenticated;
GRANT ALL ON public.assets TO service_role;
ALTER TABLE public.chapter_pages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.chapter_pages FROM anon, authenticated;
GRANT ALL ON public.chapter_pages TO service_role;
ALTER TABLE public.upload_jobs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.upload_jobs FROM anon, authenticated;
GRANT ALL ON public.upload_jobs TO service_role;
ALTER TABLE public.upload_items ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.upload_items FROM anon, authenticated;
GRANT ALL ON public.upload_items TO service_role;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.audit_logs FROM anon, authenticated;
GRANT ALL ON public.audit_logs TO service_role;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.site_settings FROM anon, authenticated;
GRANT ALL ON public.site_settings TO service_role;
ALTER TABLE public.login_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.login_attempts FROM anon, authenticated;
GRANT ALL ON public.login_attempts TO service_role;
ALTER TABLE public.view_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.view_events FROM anon, authenticated;
GRANT ALL ON public.view_events TO service_role;
GRANT SELECT ON public.titles TO anon, authenticated;
GRANT SELECT ON public.title_alt_names TO anon, authenticated;
GRANT SELECT ON public.genres TO anon, authenticated;
GRANT SELECT ON public.title_genres TO anon, authenticated;
GRANT SELECT ON public.chapters TO anon, authenticated;
GRANT SELECT ON public.chapter_pages TO anon, authenticated;
GRANT SELECT ON public.assets TO anon, authenticated;
CREATE POLICY titles_read ON titles FOR SELECT USING ((visibility='Published' AND deleted_at IS NULL) OR public.inkora_can_edit(id));
CREATE POLICY alt_names_read ON title_alt_names FOR SELECT USING (public.inkora_public_title(title_id) OR public.inkora_can_edit(title_id));
CREATE POLICY genres_read ON genres FOR SELECT USING (true);
CREATE POLICY title_genres_read ON title_genres FOR SELECT USING (public.inkora_public_title(title_id) OR public.inkora_can_edit(title_id));
CREATE POLICY chapters_read ON chapters FOR SELECT USING (public.inkora_public_chapter(id) OR public.inkora_can_edit(title_id));
CREATE POLICY pages_read ON chapter_pages FOR SELECT USING (public.inkora_public_chapter(chapter_id) OR EXISTS(SELECT 1 FROM chapters c WHERE c.id=chapter_id AND public.inkora_can_edit(c.title_id)));
CREATE POLICY assets_read ON assets FOR SELECT USING ((public.inkora_public_title(title_id) AND (chapter_id IS NULL OR public.inkora_public_chapter(chapter_id))) OR public.inkora_can_edit(title_id));
-- Private originals and drafts. No public storage policies and no anonymous listing.
INSERT INTO storage.buckets (id,name,public,file_size_limit) VALUES ('inkora-private','inkora-private',false,314572800) ON CONFLICT(id) DO NOTHING;

ALTER TABLE titles ADD CONSTRAINT title_cover_fk FOREIGN KEY(cover_id) REFERENCES assets(id) ON DELETE SET NULL;
ALTER TABLE titles ADD CONSTRAINT title_banner_fk FOREIGN KEY(banner_id) REFERENCES assets(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS alt_names_title ON title_alt_names(title_id);
CREATE INDEX IF NOT EXISTS assets_chapter ON assets(chapter_id);
CREATE INDEX IF NOT EXISTS assets_title ON assets(title_id);
CREATE INDEX IF NOT EXISTS upload_jobs_user ON upload_jobs(user_id,created_at);
CREATE INDEX IF NOT EXISTS upload_items_job ON upload_items(job_id,status,position);
CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS title_editors_user ON title_editors(user_id,title_id);
